variables:
  URL: 'gitlab.ums.ac.id:5050/mhi595/helpdesk-bpsdm:v1.0'

stages:
  - build
  # - update


before_script:
  - echo "GETTING STARTED STAGE..."
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

after_script:
  - docker push $URL
  - echo "COMPLETE STAGE..."


Build Image:
  stage: build
  script:
    - docker build -t $URL .
  only:
    refs:
      - main
