# ============================
#            SERVER
# ============================

# version: '3.7'

# services:
#   web:
#     image: <link image gitlab> # contoh: gitlab.ums.ac.id:5050/rr867/monev-jurnal:v1.0
#     command: python manage.py runserver 0.0.0.0:8000
#     ports:
#       - 8013:8000 # sesuaikan port dengan port yang belum terpakai
#     restart: always
#     volumes:
#       - media:/home/app/webapp/media/
#     networks:
#       - lan
#     environment: # setting environment disini atau di setting.py (config default)
#       - SECRET_KEY=secret_key
#       - DEBUG=False
#       - ALLOWED_HOSTS=*
#       - DB_ENGINE=db_engine
#       - DB_NAME=db_name
#       - DB_USER=db_user
#       - DB_PASSWORD=db_password
#       - DB_HOST=db_host
#       - DB_PORT=db_port
#       - APP_BASE_URL=base_url
#       - API_GATEWAY_URL=http://172.16.10.241:8008
#       - API_GATEWAY_USERNAME=api_username
#       - API_GATEWAY_PASSWORD=api_password
#       - API_STAR_URL=https://star.ums.ac.id/abubakar/
#       - API_STAR_USERNAME=username
#       - API_STAR_PASSWORD=password
#       - EMAIL_HOST_USER=email_user
#       - EMAIL_HOST_PASSWORD=email_password
#       - WABLAS_URL=https://eu.wablas.com
#       - WABLAS_TOKEN=token
    
# networks:
#   lan:
#     external:
#       name: arsip-network # sesuaikan network

# volumes:
#   media:


# ============================
#            LOCAL
# ============================
version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000

    ports:
      - 8000:8000
    volumes:
      - ./project:/home/app/webapp
