# Generated by Django 4.2 on 2024-01-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketstate',
            name='code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketstate',
            name='priority',
            field=models.SmallIntegerField(default=1),
        ),
    ]
