# Generated by Django 4.2 on 2024-01-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_ticketstate_code_ticketstate_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketstate',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketstate',
            name='priority',
            field=models.SmallIntegerField(default=1, unique=True),
        ),
    ]
