# Generated by Django 4.2 on 2024-01-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0003_alter_ticketstate_code_alter_ticketstate_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='ticketing/attachments'),
        ),
    ]
