# Generated by Django 4.2 on 2024-01-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0004_alter_ticket_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketanswer',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='ticketing/answers'),
        ),
    ]
